### ISSUE TITLE
Error not being logged

### ISSUE THREAD

**Issue by mkanoor** [ManageIQ/topological_inventory-openshift#50]
Debugging operations worker we are not logging the error message here
https://github.com/ManageIQ/topological_inventory-openshift/blob/16e6f5fe3fd547382ffaecd41580cd30bacd597a/lib/topological_inventory/openshift/operations/worker.rb#L75

```
{"@timestamp":"2019-03-22T18:16:33.707795 ","hostname":"topological-inventory-openshift-operations-20-66czh","pi    d":1,"tid":"34cf60","level":"err","message":"/usr/local/lib/ruby/gems/2.4.0/bundler/gems/topological_inventory-a    pi-client-ruby-527c1660c0ef/lib/topological_inventory-api-client/api_client.rb:65:in `call_api'\n/usr/local/lib/    ruby/gems/2.4.0/bundler/gems/topological_inventory-api-client-ruby-527c1660c0ef/lib/topological_inventory-api-cl    ient/api/default_api.rb:5456:in `update_task_with_http_info'\n/usr/local/lib/ruby/gems/2.4.0/bundler/gems/topolo    gical_inventory-api-client-ruby-527c1660c0ef/lib/topological_inventory-api-client/api/default_api.rb:5413:in `up    date_task'\n/opt/openshift-collector/lib/topological_inventory/openshift/operations/worker.rb:80:in `update_task    '\n/opt/openshift-collector/lib/topological_inventory/openshift/operations/worker.rb:75:in `rescue in order_serv    ice'\n/opt/openshift-collector/lib/topological_inventory/openshift/operations/worker.rb:49:in `order_service'\n/    opt/openshift-collector/lib/topological_inventory/openshift/operations/worker.rb:42:in `process_message'
```

**Comment by mkanoor** [comment]
@agrare @eclarizio 
Please review
